### ISSUE TITLE
Scary tracebacks from network errors

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/project-summary#3]
Periodically I get cron emails like this:

```
/etc/cron.hourly/mg-project-summary:
HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 145, in _handle_expired_response
    return self._send_and_cache(request, cache_key, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 157, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/summary.py", line 1563, in main
    print_html_report(projects, config, args.output_file)
  File "/opt/project-summary/summary.py", line 1604, in print_html_report
    html = template.render_unicode(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/mako/template.py", line 478, in render_unicode
    return runtime._render(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/mako/runtime.py", line 942, in _exec_template
    _render_error(template, context, compat.exception_as())
  File "/opt/project-summary/.env/lib/python3.8/site-packages/mako/runtime.py", line 952, in _render_error
    result = template.error_handler(context, error)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/mako/runtime.py", line 940, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f0df8c22fa0", line 77, in render_body
    __M_writer(filters.html_escape(column.td(project)))
    # memory:0x7f0df8c22fa0 line 93 in render_body:
    #                 ${column.td(project)}
  File "/opt/project-summary/summary.py", line 982, in td
    return html('td', self.inner_html(project), class_=self.css_class,
  File "/opt/project-summary/summary.py", line 1058, in inner_html
    url, image_url, status = self.get_status(project)
  File "/opt/project-summary/summary.py", line 1157, in get_status
    project.coverage('{}%', 'unknown'),
  File "/opt/project-summary/summary.py", line 641, in coverage
    if self.coverage_number is None:
  File "/opt/project-summary/summary.py", line 67, in __get__
    value = self.fn(obj)
  File "/opt/project-summary/summary.py", line 628, in coverage_number
    res = self._http_get(url, allow_redirects=False)
  File "/opt/project-summary/summary.py", line 413, in _http_get
    return self.session.get(url, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 88, in request
    response = super().request(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 127, in send
    return self._handle_expired_response(request, response, cache_key, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 145, in _handle_expired_response
    return self._send_and_cache(request, cache_key, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 157, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0df8c053a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
run-parts: /etc/cron.hourly/mg-project-summary exited with return code 1
```

and this looks scary for no good reason.

What should happen instead (option 1):

- `sys.exit(f'coveralls.io is not reachable:\n{exc}' )`

What should happen instead (option 2):

- render the page, but show "coverage: unavailable" or something?  maybe cache coverage numbers from previous runs?

**Comment by mgedmin** [comment]
Now I get both a series of tracebacks and a short message at the end?  What the heck???

```
/etc/cron.hourly/mg-project-summary:
From https://github.com/mgedmin/mgp2pdf
   000e3e4..cbcb174  master     -> origin/master
HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7fdc7b6820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7fdc7b6820>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/project-summary/.env/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7fdc7b6820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 145, in _handle_expired_response
    return self._send_and_cache(request, cache_key, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests_cache/session.py", line 157, in _send_and_cache
    response = super().send(request, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/project-summary/.env/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7fdc7b6820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
Network error: HTTPSConnectionPool(host='coveralls.io', port=443): Max retries exceeded with url: /repos/mgedmin/check-manifest/badge.svg?branch=master (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7fdc7b6820>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
run-parts: /etc/cron.hourly/mg-project-summary exited with return code 1
```

**Comment by mgedmin** [comment]
The chain of tracebacks is logged by [requests-cache](https://github.com/reclosedev/requests-cache/blob/8935f4bce6011ee75ac821edd9f91f0f5a096f6b/requests_cache/session.py#L155).

**Comment by mgedmin** [comment]
I suppose I could configure logging to suppress all errors from requests_cache, but I don't want to do that in case it logs something important.

**Comment by mgedmin** [comment]
requests-cache 0.7.0 will suppress the traceback logging.
